// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Segfy_HandsOn.Models;

namespace SegfyHandsOn.Migrations
{
    [DbContext(typeof(DB.SegurosDbContext))]
    [Migration("20180824001012_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("Segfy_HandsOn.Models.Seguro", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("clienteId");

                    b.Property<string>("objetoId");

                    b.Property<int>("tipoSeguro");

                    b.HasKey("id");

                    b.ToTable("Seguros");
                });
#pragma warning restore 612, 618
        }
    }
}
